spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campuxo
    username: postgres
    password: Adi@758493
    hikari:
      connection-timeout: 30000
      max-lifetime: 300000
      minimum-idle: 1
      maximum-pool-size: 10

  sql:
    init:
      mode: never

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: false
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true

jwt:
  secret: VqChmzuV2ojiCUrmZw71b2gZIfStoqMub/uIhS1SV5M=
  expiration: 86400000

vapid:
  public-key: BDATZ9GXWjobHYwLCh-u4FQUMkXlbznopEdnBbBoL2PG77qcSpM8k-tAYzdcQP_HYvP7movh4UAbmK2zP1WYsrk
  private-key: vL6bUC9aeyM2V5G1leuAW0dC8AKOlWHafGJtSt3M_94
  subject: mailto:admin@campuxo.com
