spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campuxo
    username: postgres
    password: Adi@758493
    hikari:
      connection-timeout: 30000
      max-lifetime: 300000
      minimum-idle: 1
      maximum-pool-size: 10

  sql:
    init:
      mode: never

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: false
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true

jwt:
  secret: VqChmzuV2ojiCUrmZw71b2gZIfStoqMub/uIhS1SV5M=
  expiration: 86400000
