import { apiSlice } from '../../../app/store/apiSlice';

const BASE = '/api/v1/students';

export const studentApi = apiSlice.injectEndpoints({
  endpoints: (b) => ({
    getStudents:      b.query({ query: (params) => ({ url: BASE, params }), providesTags: ['Student'] }),
    getStudentById:   b.query({ query: (id) => `${BASE}/${id}`, providesTags: ['Student'] }),
    getMyProfile:     b.query({ query: () => `${BASE}/me`, providesTags: ['Student'] }),
    getMyCourses:     b.query({ query: () => `${BASE}/me/courses` }),
    getMyStats:       b.query({ query: () => `${BASE}/me/stats` }),
    getMyAlerts:      b.query({ query: () => `${BASE}/me/alerts` }),
    getMyAttendance:  b.query({ query: () => '/api/v1/attendance/me' }),
    getMyIAMarks:     b.query({ query: ({ courseId, classStructureId }) => `${BASE}/me/ia?courseId=${courseId}&classStructureId=${classStructureId}` }),
    getMyAssignment:  b.query({ query: ({ courseId, classStructureId }) => `${BASE}/me/ia/assignments?courseId=${courseId}&classStructureId=${classStructureId}` }),
    getMySeminar:     b.query({ query: ({ courseId, classStructureId }) => `${BASE}/me/ia/seminars?courseId=${courseId}&classStructureId=${classStructureId}` }),
    getMyFinalMarks:  b.query({ query: ({ courseId, classStructureId }) => `${BASE}/me/ia/final-marks?courseId=${courseId}&classStructureId=${classStructureId}` }),
    getMyClassStructureId: b.query({ query: () => `${BASE}/me/ia/class-structure-id` }),
    getMyClassmates:       b.query({ query: (courseId) => `${BASE}/me/courses/${courseId}/classmates` }),
    getAllClasses:     b.query({ query: () => '/api/v1/classes', providesTags: ['Class'] }),
    getAllDepartments:  b.query({ query: () => '/api/v1/departments', providesTags: ['Department'] }),
    createDepartment:  b.mutation({ query: (name) => ({ url: '/api/v1/departments', method: 'POST', body: { name } }), invalidatesTags: ['Department'] }),
    deleteDepartment:  b.mutation({ query: (name) => ({ url: `/api/v1/departments?name=${encodeURIComponent(name)}`, method: 'DELETE' }), invalidatesTags: ['Department'] }),
    getClassCourses:   b.query({ query: (classId) => `/api/v1/classes/${classId}/courses`, providesTags: ['Class', 'Course'] }),
    getPrograms:      b.query({ query: () => '/api/v1/courses/programs' }),
    getCoursesByProgram: b.query({ query: (program) => `/api/v1/courses/programs/${program}`, providesTags: ['Course'] }),
    getSpecializations: b.query({ query: (params) => ({ url: '/api/v1/specializations', params }), providesTags: ['Specialization'] }),
    getBatchesByDepartment: b.query({ query: (department) => ({ url: '/api/v1/classes/public', params: { department } }), providesTags: ['Class'] }),
    createSpecialization: b.mutation({ query: (data) => ({ url: '/api/v1/specializations', method: 'POST', body: data }), invalidatesTags: ['Specialization'] }),
    deleteSpecialization: b.mutation({ query: (id) => ({ url: `/api/v1/specializations/${id}`, method: 'DELETE' }), invalidatesTags: ['Specialization'] }),

    createStudent:    b.mutation({ query: (data) => ({ url: BASE, method: 'POST', body: data }), invalidatesTags: ['Student'] }),
    adminCreateStudent: b.mutation({ query: (data) => ({ url: `${BASE}/admin`, method: 'POST', body: data }), invalidatesTags: ['Student'] }),
    updateStudent:    b.mutation({ query: ({ id, ...data }) => ({ url: `${BASE}/${id}`, method: 'PUT', body: data }), invalidatesTags: ['Student'] }),
    deleteStudent:    b.mutation({ query: (id) => ({ url: `${BASE}/${id}`, method: 'DELETE' }), invalidatesTags: ['Student'] }),
    updateMyProfile:  b.mutation({ query: (data) => ({ url: `${BASE}/me`, method: 'PUT', body: data }), invalidatesTags: ['Student'] }),
    uploadMyPhoto:    b.mutation({ query: (formData) => ({ url: `${BASE}/me/photo`, method: 'POST', body: formData }), invalidatesTags: ['Student'] }),
    enrollCourse:     b.mutation({ query: (courseId) => ({ url: `/api/v1/courses/${courseId}/enroll`, method: 'POST' }), invalidatesTags: ['Course'] }),
    unenrollCourse:   b.mutation({ query: (courseId) => ({ url: `/api/v1/courses/${courseId}/enroll`, method: 'DELETE' }), invalidatesTags: ['Course'] }),
    createClass:      b.mutation({ query: (data) => ({ url: '/api/v1/classes', method: 'POST', body: data }), invalidatesTags: ['Class'] }),
    updateClass:      b.mutation({ query: ({ id, ...data }) => ({ url: `/api/v1/classes/${id}`, method: 'PUT', body: data }), invalidatesTags: ['Class'] }),
    deleteClass:      b.mutation({ query: (id) => ({ url: `/api/v1/classes/${id}`, method: 'DELETE' }), invalidatesTags: ['Class'] }),
    assignCoursesToClass: b.mutation({ query: ({ classId, courseIds }) => ({ url: `/api/v1/classes/${classId}/courses`, method: 'POST', body: { courseIds } }), invalidatesTags: ['Class', 'Course'] }),
    removeCourseFromClass: b.mutation({ query: ({ classId, courseId }) => ({ url: `/api/v1/classes/${classId}/courses/${courseId}`, method: 'DELETE' }), invalidatesTags: ['Class', 'Course'] }),
  }),
});

export const {
  useGetStudentsQuery,
  useGetStudentByIdQuery,
  useGetMyProfileQuery,
  useGetMyCoursesQuery,
  useGetMyStatsQuery,
  useGetMyAlertsQuery,
  useGetMyAttendanceQuery,
  useGetMyIAMarksQuery,
  useGetMyAssignmentQuery,
  useGetMySeminarQuery,
  useGetMyFinalMarksQuery,
  useGetMyClassStructureIdQuery,
  useGetMyClassmatesQuery,
  useGetAllClassesQuery,
  useGetAllDepartmentsQuery,
  useCreateDepartmentMutation,
  useDeleteDepartmentMutation,
  useGetClassCoursesQuery,
  useGetProgramsQuery,
  useGetCoursesByProgramQuery,
  useGetSpecializationsQuery,
  useGetBatchesByDepartmentQuery,
  useCreateSpecializationMutation,
  useDeleteSpecializationMutation,
  useCreateStudentMutation,
  useAdminCreateStudentMutation,
  useUpdateStudentMutation,
  useDeleteStudentMutation,
  useUpdateMyProfileMutation,
  useUploadMyPhotoMutation,
  useEnrollCourseMutation,
  useUnenrollCourseMutation,
  useCreateClassMutation,
  useUpdateClassMutation,
  useDeleteClassMutation,
  useAssignCoursesToClassMutation,
  useRemoveCourseFromClassMutation,
} = studentApi;
